#!/bin/bash
curl -O https://storage.googleapis.com/golang/go1.13.8.linux-amd64.tar.gz
tar -xvf go1.13.8.linux-amd64.tar.gz
sudo chown -R root:root ./go
sudo mv go /usr/local
export GOPATH=$HOME/go_projects
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
echo "export GOPATH=$HOME/go_projects" >> ~/.profile
echo "export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin" >> ~/.profile
source ~/.profile
cd ~
mkdir go_projects
